customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    # path('contact/',views.contact,name='contact'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('register/',views.register,name='register'),
    path('men/',views.men,name='men'),
    path('woman/',views.woman,name='woman'),
    path('masterpage/',views.masterpage,name='masterpage'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/',views.remove_from_cart,name='remove_from_cart'),
    path('payment/',views.payment,name='payment'),
    path('mobile/',views.mobile,name="mobile"),
    path('myaccount/',views.myaccount,name='myaccount')
]

fashionous_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),

]+static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns =[
    path('s_home/',views.s_home,name='s_home'),
    path('s_register/',views.s_register,name='s_register'),
    path('s_login/',views.s_login,name='s_login'),
    path('s_logout/',views.s_logout,name='s_logout'),
    path('add_product/',views.add_product,name='add_product'),
    path('view_product/',views.view_product,name='view_product'),
    path('update_product/',views.update_product,name='update_product'),
    path('remove/<int:pid>',views.remove,name='remove'),
    path('update/<int:pid>',views.update_product,name='update_product'),
    path('s_myaccount/',views.s_myaccount,name='s_myaccount')
]

customer/models.py
from django.db import models
from seller.models import *

# Create your models here.
class Customer(models.Model):
    email=models.EmailField(null=True)
    password=models.TextField(max_length=100,null=True)
    firstname=models.TextField(max_length=100,null=True)
    lastname=models.TextField(max_length=100,null=True)
    
class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField(default=1)
    

customer/views.py
from django.shortcuts import render, redirect
from customer.models import *
from django.contrib import messages
from django.http import HttpResponse
# Create your views here.
def home(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust=Customer.objects.get(id=customer_id)
        customer=cust.firstname
        customer=customer[0]
    return render(request,'customer/home.html')
def about(request):
    return render(request,'customer/about.html')
def mobile(request):
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        contact=request.POST['contact']
        text=request.POST['text']
        mob=Customer(name=name,email=email,contact=contact,text=text)
        mob.save()
    return render(request,'customer/mobile.html')
def login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['psd']
        try:
            cust=Customer.objects.get(email=email,password=password)
            request.session['customer']=cust.id
            return redirect('customer:home')
        except Customer.DoesNotExist:
            return render(request,'customer/login.html',{'msg':'invalid password'})
    return render(request,'customer/login.html')
    
def logout(request):
    if 'customer' in request.session:
        del request.session['customer']
        return redirect('customer:login')
def register(request): 
    if request.method=='POST':
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        password=request.POST['password']
        email=request.POST['email']
      
        cust=Customer(firstname=firstname,lastname=lastname,password=password,email=email)
        
        cust.save()
        messages.success(request,'Registered Successfully!')
        
        return render(request,'customer/register.html')
        
    return render(request,'customer/register.html')
        
    
def men(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cat=Category.objects.get(name='men')
        pdt=Product.objects.filter(category=cat)
        cust=Customer.objects.get(id=customer_id)
        customer=cust.firstname
        customer=customer[0]
    
    return render(request,'customer/men.html',{'pdt':pdt,'cust':customer})
def woman(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust=Customer.objects.get(id=customer_id)
        cat=Category.objects.get(name='woman')
        pdt=Product.objects.filter(category=cat)
        customer=cust.firstname
        customer=customer[0]
    
        return render(request,'customer/woman.html',{'pdt':pdt,'customer':cust,'cust':customer})
    else:
        return redirect('customer:home')
def masterpage(request):
    return render(request,'customer/masterpage.html')
def add_to_cart(request,product_id):
    if request.method=='POST':
        product=Product.objects.get(id=product_id)
        cart_item,created=Cart.objects.get_or_create(product=product)
        if not created:
            cart_item.quantity+=1
            cart_item.save()
    return redirect('customer:cart')

def cart(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust=Customer.objects.get(id=customer_id)
        cart_items=Cart.objects.all()
        total_price=sum(item.product.price*item.quantity for item in cart_items)
        total_price_per_item=[]
        grand_total=0
    for i in cart_items:
        tot=i.product.price * i.quantity
    for item in cart_items:
        item_total=item.product.price*item.quantity
        total_price_per_item.append({'item':item,'total':'item_total'})
        grand_total+=item_total
    customer=cust.firstname
    customer=customer[0]
    return render(request,'customer/cart.html',{'cart_items':cart_items,'grand_total':grand_total,'total_price':total_price,'item_total':item_total,'tot':tot,'cust':customer})
def remove_from_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    cart_item=Cart.objects.get(product=product)
    cart_item.delete()
    return redirect('customer:cart')


def payment(request):
    return render(request,'customer/payment.html')
def myaccount(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust=Customer.objects.get(id=customer_id)

    return render(request,'customer/myaccount.html',{'customer':cust})

customer/templates/customer/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/about.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        .container{
    background-color: #FDFEFE   ;
    height: 1250px;
}
        #row1{
            height: 100px;
            background-color:#BDBDBD;
        }
        #table1{
            margin-top: 30px;
            margin-left: 0px;
        }
    .butn:hover{
         background-color: red;
         color:#fff;
         border-radius: 3px;
         font-style: italic;
    }
    .butn:hover{
        color: white;
    }
    .col-4 img{
        width: 250px;
        mix-blend-mode: color-burn;
        margin-left: 0px;
    }
    #row3 h5{
        font-weight: 700;
    }
    #row3{
        margin-top: 50px;
    }
    </style>
</head>
<body>
    <div class="container" style="height: 1100px;">
        <div class="row" id="row1">
            <div class="col-4">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="">
            </div>
            <div class="col-8">
                <table id="table1">
                    <tr>
                        
                        <th><button><a href="{% url 'customer:home' %}">HOME</a></button></th>
                        <th><div class="dropdown">
                            <a style=" text-decoration: none; padding: 4px; color: black;" class="butn dropdown-toggle shopebutn" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              SHOPE
                            </a>
                          
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'customer:men' %}">MEN</a></li>
                              <li><a class="dropdown-item" href="{% url 'customer:woman' %}">WOMAN</a></li>
                            </ul>
                          </div></th>
                        <th><button><a href="{% url 'customer:mobile' %}">CONTACT</a></button></th>
                        <th><button><a href="{% url 'customer:about' %}">ABOUT</a></button></th>
                        <th><button><a href="{% url 'customer:login' %}">LOGIN</a></button></th>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-12">
                <h1 style="color: black" >𝑨𝒃𝒐𝒖𝒕 𝑼𝒔</h1><br>
                <p><span>THE FASHIONOUS SHOP </span>caters to toughtful shoppers who appreciate unique designs and top quality pieces you just can't find anywhere else. we are constantly curating fresh new collections and looking for the next big thing to our customers will love. <br>
                    founded in vienna in 2024,we are proud to be your online clothing shop that you can rely on for our expert service and care. <br>
                    * our mission is to make a difference through our branding by staying ahead  of the fashion trends, defining style and giving customers what they want <br>
                    * our vision is to change the way our society connects with the fashion industry by providing our customers with product that are ethically and responsibly sourced. <br>
                    
                </p>
                <p id="para">
                    * our aim is to provide clothes for all sizes
                </p>
                
                </div>
        </div>
        <div class="row" id="row3">
            <div class="col-5">
                <img src="{% static 'images/about3.jpg' %}" alt="" height="500px" width="400px">
            </div>
            <div class="col-7">
                <h5>Introduction:</h5>
                <p style="font-size: large;text-indent: 0px;"><span>FASHIONOUS</span> is a one stop shop for all your fashion and lifestyle needs. Being India's largest e-commerce store for fashion and lifestyle products, fashionous aims at providing a hassle free and enjoyable shopping experience to shoppers across the country with the widest range of brands and products on its portal.
                     The brand is making a conscious effort to bring the power of fashion to shoppers with an array of the latest and trendiest products available in the country</p>
                <h5>Recognitions:</h5>
                <ul>
                    <li>Awarded 'Fashion eRetailer of the Year 2013' by Franchise India – Indian eRetail Awards</li>
                    <li> Awarded 'Best E-commerce Website for 2012' by IAMAI – India Digital Awards</li>
                    <li> Awarded 'Images Most Admired Retailer of the Year: Non–Store Retail' for 2012 by Images Group</li>
                    <li>  Awarded 'Best E-commerce Partner of the year 2011-12' by Puma India
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>

customer/templates/customer/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style/cart.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js">
    <style>
        #row3 td button{
    align-items: center;
    background-color:skyblue;
    font-style: italic;
    font-size:large ;
    font-weight: 700;
    border-radius: 3px;
   margin-right: -600px;
}
    #row3 button:hover{
    opacity: 0.5;
}
    #profile{
            height: 35px;
            width: 35px;
            border-radius: 17px;
            background-color: #04C8C8;
        }
        #profile a{
            text-align: center;
            font-size: larger;
            color: white;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row" id="row1">
            <div class="col-4">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="" style="width: 200px; mix-blend-mode:darken;">

            </div>
            <div class="col-8">
                <table id="table1">
                    <tr>
                        
                        <th><button><a href="{% url 'customer:home' %}">HOME</a></button></th>
                        <th><div class="dropdown">
                            <a style=" text-decoration: none; padding: 4px; color:white;" class="butn dropdown-toggle shopebutn" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              SHOPE
                            </a>
                          
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'customer:men' %}">MEN</a></li>
                              <li><a class="dropdown-item" href="{% url 'customer:woman' %}">WOMAN</a></li>
                            </ul>
                          </div></th>
                        <th><button><a href="{% url 'customer:mobile' %}">CONTACT</a></button></th>
                        <th><button><a href="{% url 'customer:about' %}">ABOUT</a></button></th>
                        <th><button><a href="{% url 'customer:login' %}">LOGIN</a></button></th>
                        <th><div id="profile"><a href="{% url 'customer:myaccount' %}">{{cust}}</a></div></th>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-12">
                <table>
                    <tr>
                        <th>Cart</th>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                    {% for item in cart_items %}
                    <tr>
                        <td><img src="{{item.product.image.url}}" alt="" height="200px" width="150px"></td>
                        <td>{{item.product.name}}</td>
                        <td id="">{{item.quantity}}</td>
                        <td id="total">{{item.product.price}}</td>

                        
                        <div style="display: none;">
                            <input type="number" name="" id="quantity" value="{{item.quantity}}">
                            <input type="number" name="" id="price" value="{{item.product.price}}">

                        </div>
                       <td><a href="{% url 'customer:remove_from_cart' item.product.id %}" style="color: black;"><i class="fa-solid fa-trash"></i></a></td> 
                    </tr> 
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="row" id="row3">
            <div class="col-4"></div>
            <div class="col-8">
                <table>
                    <tr>
                        <td ></td>
                        <td></td>
                        <td><i>Total</i></td>
                        <td>{{grand_total}}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td><button><a href="{% url 'customer:payment' %}">Pay now</a></button></td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<script>





</script>

</body>
</html>

customer/templates/customer/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/home.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&family=Roboto+Slab&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<style>
  .table td button a{
    text-decoration: none; color:black;
  }
  .table td button a:hover{
    color: white;
  }
 .container table td a{
  width: 100px;
 }
 .col-4 img{
  width: 300px;

 }
 #profile{
            height: 35px;
            width: 35px;
            border-radius: 17px;
            background-color: rosybrown;
        }
        #profile a{
            text-align: center;
            font-size: larger;
            color: white;
            padding-left: 10px;
        }
</style>
</head>
<body>
    <div class="container">
        <div class="row" class="row1">
            <div class="col-4">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="">
            </div>
            <div class="col-8">
                <table class="table">
                  
                    <tr>
                       <td><button><a href="{% url 'customer:home' %}">Home</a></button></td>
                       <!-- <td><select name="" id="">
                        <option value="">Shop</option>
                        <option value=""><a href="{% url 'customer:men' %}">Men</a></option>
                        <option value=""><a href="{% url 'customer:woman' %}">Woman</a></option>
                       </select></td> -->
                       <td><div class="dropdown">
                        <a style=" text-decoration: none; padding: 4px;" class="butn dropdown-toggle shopebutn" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Shope
                        </a>
                      
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'customer:men' %}">Men</a></li>
                          <li><a class="dropdown-item" href="{% url 'customer:woman' %}">Woman</a></li>
                        </ul>
                      </div></td>
                      <td><div class="dropdown">
                        <a style=" text-decoration: none; padding: 4px;" class="butn dropdown-toggle shopebutn" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Contact us
                        </a>
                      
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'customer:mobile' %}">Contact us</a></li>
                          <li><a class="dropdown-item" href="{% url 'customer:about' %}">About</a></li>
                        
                        </ul>
                      </div></td>
                  
                       <!-- <td><button><a href="{% url 'customer:mobile' %}">Contact us</a></button></td>
                       <td><button><a href="{% url 'customer:about' %}" >About</a></button></td> -->
                       <!-- <td><button><a href="{% url 'customer:login' %}">Login</a></button></td> -->
                       <!-- <td><button><a href="{% url 'customer:logout' %}">Logout</a></button></td> -->
                       <td><div class="dropdown">
                        <a style=" text-decoration: none; padding: 4px;" class="butn dropdown-toggle shopebutn" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Login
                        </a>
                      
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'customer:login' %}">Login</a></li>
                          <li><a class="dropdown-item" href="{% url 'customer:logout' %}">Logout</a></li>
                        
                        </ul>
                      </div></td>
                      <td><button><a href="{% url 'seller:s_home' %}">Seller</a></button></td>

                       <td><button><a href="{% url 'customer:cart' %}" style="text-decoration: none;">Cart</a></button></td>
                       <td><div id="profile" style="margin-top: -5px;"><a href="{% url 'customer:myaccount' %}"><i class="fa-regular fa-user"></i></a></div></td>                     
                    </tr>
                </table>
                
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-6" id="col-6">
                <h5>OFFER CLOSESS SOON 2k24</h5>
                <h1>SALE UP TO </h1>
                <P>50% OFF</P>
                <p id="para">NEW <br>Collection <br>For Everyone</p>
                <button type="button" class="btn btn-danger">Shop Now</button>
               
            </div>
            <div class="col-6">
                <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="{% static 'images/img2.jpg' %}" id="img2" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'images/img3.jpg' %}" id="img3" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'images/img4.jpg' %}" id="img4" class="d-block w-100" alt="...">
                      </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
            </div>
        </div>
        <div class="row" id="row3">
          <div class="col-12">
            <h1>𝓣𝓲𝓬𝓴 , 𝓽𝓸𝓬𝓴, 𝓽𝓲𝓶𝓮 𝓽𝓸 𝓼𝓱𝓸𝓹!</h1>
            <p id="para1"><b>"STYLE <br></b>IS A WAY TO SAY  <b> WHO YOU ARE </b> WITHOUT HAVING <br>TO  <b>SPEAK "</b></p>
          </div>
        </div>
        <div class="row" id="row4">
          <div class="col-4">
            <img src="{% static 'images/img30.jpg' %}" alt="" id="img1">
          </div>
          <div class="col-4">
            <img src="{% static 'images/img12.jpg' %}" alt="" id="img2">
          </div>
          <div class="col-4">
            <img src="{% static 'images/img25.jpg' %}" alt="" id="img3">
          </div>
        </div><br>
        <h1 id="fashion">"𝐹𝒶𝓈𝒽𝒾𝑜𝓃 𝐻𝒶𝓈 𝒯𝑜 𝑅𝑒𝒻𝓁𝑒𝒸𝓉𝑒𝒹 𝒲𝒽𝑜 𝒜𝓇𝑒 𝒴𝑜𝓊</h1>
        <div class="row" id="row5">
          <div class="col-4">
            <img src="{% static 'images/img11.png' %}" alt="" id="imgrow5">
          </div>
          <div class="col-4">
            <h4>𝑫𝒐𝒏'𝒕 𝑪𝒉𝒂𝒏𝒈𝒆 𝒕𝒐 𝒇𝒊𝒕 𝒕𝒉𝒆  <br>𝑭𝒂𝒔𝒉𝒊𝒐𝒏. 𝑪𝒉𝒂𝒏𝒈𝒆 𝒕𝒉𝒆 <br>𝑭𝒂𝒔𝒉𝒊𝒐𝒏  𝒕𝒐 𝑭𝒊𝒕 𝒀𝒐𝒖 ,<br>𝑰𝒇 𝒀𝒐𝒖 𝑪𝒂𝒏'𝒕 𝒃𝒆  𝑩𝒆𝒕𝒕𝒆𝒓 𝒕𝒉𝒂𝒏 <br>𝒀𝒐𝒖𝒓 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒐𝒏, 𝑱𝒖𝒔𝒕 𝑫𝒓𝒆𝒔𝒔 𝑩𝒆𝒕𝒕𝒆𝒓..</h4>
          </div>
          <div class="col-4">
            <img src="{% static 'images/imgfooter2.png' %}" alt="" id="imgsrow5">
          </div>
        </div>
        <div class="row" id="row6">
          <div class="col-4">
            <h4> 𝘿𝙤𝙣𝙩 𝘽𝙚 𝙄𝙣𝙩𝙤 𝙏𝙧𝙚𝙣𝙙𝙨 . <br>𝘿𝙤𝙣'𝙩 𝙈𝙖𝙠𝙚 𝙁𝙖𝙨𝙝𝙞𝙤𝙣 𝙊𝙬𝙣 𝙔𝙤𝙪, <br>𝘽𝙪𝙩 𝙔𝙤𝙪 𝘿𝙚𝙘𝙞𝙙𝙚 𝙒𝙝𝙖𝙩 𝙔𝙤𝙪 𝘼𝙧𝙚, 𝙒𝙝𝙖𝙩 𝙔𝙤𝙪 𝙒𝙖𝙣𝙩 𝙏𝙤 𝙀𝙭𝙥𝙧𝙚𝙨𝙨 𝘽𝙮 𝙏𝙝𝙚 𝙒𝙖𝙮  𝙔𝙤𝙪 𝘿𝙧𝙚𝙨𝙨 𝘼𝙣𝙙 𝙏𝙝𝙚 𝙒𝙖𝙮 𝙏𝙤 𝙇𝙞𝙫𝙚"</h4>
          </div>
          <div class="col-4">
            <img src="{% static 'images/imgfooter4.png' %}" alt="" id="imgrow6">
          </div>
          <div class="col-4"> 
            <h4 id="righth4">𝙏𝙤 𝙈𝙚, 𝘾𝙡𝙤𝙩𝙝𝙞𝙣𝙜 𝙄𝙨 𝘼. <br> 𝙁𝙤𝙧𝙢 𝙊𝙛 𝙎𝙚𝙡𝙛 𝙀𝙭𝙥𝙧𝙚𝙨𝙨𝙞𝙤𝙣  𝙏𝙝𝙚𝙧𝙚 𝘼𝙧𝙚 𝙃𝙞𝙣𝙩𝙨 𝘼𝙗𝙤𝙪𝙩 𝙒𝙝𝙤 𝙔𝙤𝙪 𝘼𝙧𝙚  𝙄𝙣 𝙒𝙝𝙖𝙩 𝙔𝙤𝙪 𝙒𝙚𝙖𝙧". 𝙁𝙖𝙨𝙝𝙞𝙤𝙣 𝙄𝙨  𝙒𝙝𝙖𝙩 𝙔𝙤𝙪 𝘿𝙤, </h4>
          </div>
        </div>
        <div class="row"  id="row7">
          <div class="col-12">
            <div id="address"> 
            <p>Address: <br>Vaishnavi Summit, Ground Floor 7th Main 80 Feet Road,<br> 3rd block, Koramangala Industrial Layout,Banglore KA IN 560034</p>
            </div>
            <div id="about">
              <p>About us: <br>We are a team of like-minded, passionate and innovative individuals with 10+ years of experience in the field of software.</p>
            </div>
            <div id="Contact">
              <p>Contact Us: <br>
                <a href="https://fashionous.in/" style="text-decoration: none; color: black;"><i class="fa-brands fa-google"></i>Google <br></a>
                <a href="https://www.instagram.com/fashionous.in?igsh=dtduMmYzcDI4MXVz" style="text-decoration: none; color: black;"><i class="fa-brands fa-instagram"></i>instagram</a><br>
                <i class="fa-brands fa-facebook"></i>facebook <br>
                <i class="fa-brands fa-twitter"></i>twitter
              </p>

            </div>
          </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>