fashionous_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),

]+static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns =[
    path('s_home/',views.s_home,name='s_home'),
    path('s_register/',views.s_register,name='s_register'),
    path('s_login/',views.s_login,name='s_login'),
    path('s_logout/',views.s_logout,name='s_logout'),
    path('add_product/',views.add_product,name='add_product'),
    path('view_product/',views.view_product,name='view_product'),
    path('update_product/',views.update_product,name='update_product'),
    path('remove/<int:pid>',views.remove,name='remove'),
    path('update/<int:pid>',views.update_product,name='update_product'),
    path('s_myaccount/',views.s_myaccount,name='s_myaccount')
]

seller/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.TextField(max_length=100,null=True)
    def __str__(self):
        return self.name
class Product(models.Model):
    name=models.TextField(max_length=100,null=True)
    description=models.TextField(max_length=100,null=True)
    quantity=models.IntegerField(null=True)
    price=models.FloatField(null=True)
    image=models.ImageField(upload_to='product',null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name
class Seller(models.Model):
    email=models.EmailField(null=True)
    password=models.TextField(max_length=100,null=True)
    firstname=models.TextField(max_length=100,null=True)
    lastname=models.TextField(max_length=100,null=True)
    

seller/views.py
from django.shortcuts import render,redirect
from . models import *
from django.contrib import messages
#from django.contrib.messages import constants as messages
# Create your views here.
def s_home(request):
    return render(request,'seller/s_home.html')
def s_register(request):
    if request.method=='POST':
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        password=request.POST['password']
        email=request.POST['email']
        sell=Seller(firstname=firstname,lastname=lastname,password=password,email=email)
        sell.save()
        messages.success(request,'Registered Successfully')
        return render(request,'seller/s_register.html')
    return render(request,'seller/s_register.html')
def s_login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        # if Seller.objects.filter(email=email,password=password).exists():
        #     return redirect('seller:s_home')
        # else:
        try:
            sell=Seller.objects.get(email=email,password=password)
            request.session['seller']=sell.id
            return redirect('seller:s_home')
        except Seller.DoesNotExist:
            return render(request,'seller/s_login.html ',{'msg':'invalid password'})
    return render(request,'seller/s_login.html')
def s_logout(request):
    if 'seller' in request.session:
        del request.session['seller']
        return redirect('seller:s_login')
def add_product(request):
    if 'seller' in request.session:
        seller_id=request.session.get('seller')
        sell=Seller.objects.get(id=seller_id)
        seller=sell.email
        seller=seller[0]
        cat=Category.objects.all()
        if request.method=='POST':
            Name=request.POST['name']
            Description=request.POST['description']
            Quantity=request.POST['quantity']
            Price=request.POST['price']
            Image=request.FILES['image']

            category_id=request.POST.get('cat')
            category=Category.objects.get(id=category_id)
            Pdt=Product(name=Name,description=Description,quantity=Quantity,price= Price,image=Image,category=category)
            Pdt.save()
            messages.success(request,'Product added successfully!')
        return render(request,'seller/add_product.html',{'cat':cat,'sell':seller})
    else:
        return render(request,'seller/s_login.html')
    
def view_product(request):
    if 'seller' in request.session:
        seller_id=request.session.get('seller')
        sell=Seller.objects.get(id=seller_id)
        seller=sell.email
        seller=seller[0]
        pdt=Product.objects.all()
        return render(request,'seller/view_product.html',{'pdt':pdt,'sell':seller})
    else:
        return render(request,'seller/s_login.html')   
    
def update_product(request,pid):
    if 'seller' in request.session:
        cat=Category.objects.all()
        product=Product.objects.get(id=pid)
        if request.method=='POST':
            name=request.POST['name']
            description=request.POST['description']
            quantity=request.POST['quantity']
            price=request.POST['price']
            image=request.FILES['image']
            product.name=name
            product.description=description
            product.quantity=quantity
            product.price=price
            product.image=image
            product.save()
            messages.success(request,'Product updated successfully!')
            return redirect('seller:view_product')
        return render(request,'seller/update_product.html',{'product':product,'cat':cat})
    else:
        return render(request,'seller/s_home.html')  

    
def remove(request,pid):
    Product.objects.get(id=pid).delete()
    return redirect('seller:view_product')
def s_myaccount(request):
    if 'seller' in request.session:
        seller_id=request.session.get('seller')
        sell=Seller.objects.get(id=seller_id)

    return render(request,'seller/s_myaccount.html',{'seller':sell})

seller/templates/seller/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <style>
        .container{
            background-color: #FBFCFC ;
            height: 650px;
        }
        #row2 table{
           
           margin-top: 50px;
        }
        input{
            font-style: italic;
            width: 200px;
        }
        label{
            font-style: italic;
        }
        select{
            font-style: italic;
            font-weight: 600;
        }
         option{
            font-style: italic;
        }
        h2{
            font-style: italic;
            color:brown;
        }
        span{
            color: red;
        }
        #row1{
            background-color:#32B6B6 ;
        }
        #row1 table tr th{
            width: 200px;
        }
        #row1 table{
            margin-left: 150px;
            margin-top: 40px;
        }
        #row1 button{
            border: none;
            background-color: #32B6B6;
        }
        button a{
            text-decoration:none;
            color: black;
            font-style: italic;
            font-weight: 700;
        }
        #row1 table button a:hover{
            background-color: black;
            color: white;
            border-radius: 3px;
            transition: .4s;
        }
        #row2 button{
            background-color: red;
            color: white;
            font-weight: 500;
            font-style: italic;
        }
        #row2 button:hover{
            opacity: 0.6;
        }
        #profile{
            height: 35px;
            width: 35px;
            border-radius: 17px;
            background-color: black;
        }
        #profile a{
            text-align: center;
            font-size: larger;
            color: white;
            text-decoration: none;
            padding-left: 12px;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="row" id="row1">
            <div class="col-3">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="" style="width: 250px; mix-blend-mode: darken;">
            </div>
            <div class="col-9">
                <form action="" method="post">
                    <table id="tabble1">
                        <tr>
                            <th><button style="margin-left: 50px;"><a href="{% url 'seller:s_home' %}">HOME</a></button></th>
                            <th><button><a href="{% url 'seller:add_product' %}">ADD PRODUCT</a></button></th>
                            <th><button><a href="{% url 'seller:view_product' %}">VIEW PRODUCT</a></button></th>
                            <!-- <th><button><a href="{% url 'seller:update_product' %}">UPDATE PRODUCT</a></button></th> -->
                            <th><button style="margin-left: 20px;"><a href="{% url 'seller:s_login' %}">LOGIN</a></button></th>
                            <th><div id="profile"><a href="{% url 'seller:s_myaccount' %}">{{sell}}</a></div></th>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-4"></div>
            <div class="col-4">
                <form action="" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th><h2>𝑨𝒅𝒅 𝒚𝒐𝒖𝒓 𝒑𝒓𝒐𝒅𝒖𝒄𝒕</h2></th>
                        </tr>
                        <tr>
                            <th><label for="">Add product <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><input type="text" name="name" placeholder="product"></th>
                        </tr>
                        <tr>
                            <th><label for="">Description <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><input type="text" name="description" placeholder="description"></th>
                        </tr>
                        <tr>
                            <th><label for="">Quantity <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><input type="number" name='quantity' placeholder="Quantity"></th>
                        </tr>
                        <tr>
                            <th><label for="">Price <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><input type="float" name="price" placeholder="price"></th>
                        </tr>
                        <tr>
                            <th><label for="">Add image <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><input type="file" name="image"></th>
                        </tr>
                        <tr>
                            <th><label for="">Select category <span>*</span></label></th>
                        </tr>
                        <tr>
                            <th><select name="cat" id="">
                                {% for i in cat %}
                                <option value="{{i.id}}">{{i.name}}</option>
                                {% endfor %}
                            </select></th>
                        </tr>
                        <tr>
                            <th><button type="submit" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">add product</button><br><p id="click"></p></th>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
  </div>
  {% if messages %}
{% for message in messages %}
    <div class="modal" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                
                
                <div class="modal-header">
                    <h6 class="modal-title" id="exampleModalLabel"> notification</h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                    <p style="color: green; font-weight: 600; font-size: larger;">{{ message }}</p>
                </div>
                <!-- <div class="modal-footer">
                </div> -->
            </div>
        </div>
    </div>
{% endfor %}
{% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
    $('#myModal').modal('show');
    });
    </script>
</body>
</html>

seller/templates/seller/s_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style/s_home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
        #row1{
            background-color: #13B6B6;
        }
        #row1 table button{
            background-color:#13B6B6;
            color: black;
            border: none;
            margin-top: 40px;
            margin-left: 0px;
        }#row1 button a{
            text-decoration: none;
            color:black;
            font-weight: 700;
            font-style: italic;
        }
        #row1 table{
            margin-left: 70px;
        }
        #row1 table tr th{
            width: 200px;

        }
         #row1 button a:hover{
            background-color: black;
            color: white;
            border-radius: 3px;
         }
         .col-8 img{
            width: 700px;
            margin-left:-11px ;
         }
         .col-4 p{
            font-size: x-large;
            font-weight: 700;
            color:#13B6B6;
            margin-top: 50px;
         }
         .col-4 span{
            font-size: large;
            color: black;
            font-weight: 700;
            font-style: italic;
         }
         .col-8 h3{
            margin-top: -397px;
            margin-left: 600px;
            font-style: italic;
            font-weight: 400;
            color: white;
         }
         #row7{
           text-align: center;
           margin-top: 132px;
          background-color:lightblue;

        }
        #address{
        width: 30%;
        float: left;
       }
       #about{
    width: 30%;
    float: left;
    text-align: center;
    padding-left: 50px;
       }
       #contact{
    width: 30%;

      }
      #row2{
        background-color:#FBFCFC ;
        height: 600px;
      }
      #row2 h1{
        margin-top: -400px;
        margin-left: 400px;
        color:#13B6B6;

      }
      #row3{
        margin-top: 70px;
        /* background-color: darkgray; */
      }
      #row3 p{
        font-size: xx-large;
        font-weight: 700;
        

      }
      #row3 img{
        border-radius: 10px;
      }
      #row4 img{
        border-radius:5px;

      }
      #row4{
        background-color: aliceblue;
      }
      #row4 p{
        font-size: larger;
        font-style: italic;
        margin-top: 30px;
        font-weight: 600;
      }
      #row4 h1{
        color:red;
        font-style: italic;

      }
      #row5{
        background-color:azure;
        margin-top: 20px;
        height: 200px;
      }
      #row5 p{
        font-size: larger;
        font-style: italic;
        margin-top: 30px;
        font-weight: 600;
      }
      #row5 img{
        border-radius:5px;
      }
      span{
        font-style: italic;
        color: red;
      }
      #row7{
        margin-top: 0px;
      }

    </style>
</head>
<body>
    <div class="container">
        <div class="row" id="row1">
            <div class="col-3">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="" style="width: 250px; mix-blend-mode: darken;">
            </div>
            <div class="col-9">
                <form action="" method="post">
                    <table id="tabble1">
                        <tr>
                            <th><button style="margin-left: 70px;"><a href="{% url 'seller:s_home' %}">HOME</a></button></th>
                            <th><button><a href="{% url 'seller:add_product' %}">ADD PRODUCT</a></button></th>
                            <th><button><a href="{% url 'seller:view_product' %}">VIEW PRODUCT</a></button></th>
                            <!-- <th><button><a href="{% url 'seller:update_product' %}">UPDATE PRODUCT</a></button></th> -->
                            <th><button style="margin-left: 30px;"><a href="{% url 'seller:s_login' %}">LOGIN</a></button></th>
                            <th><button style=""><a href="{% url 'seller:s_logout' %}">LOGOUT</a></button></th>

                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-8">
                <img src="{% static 'images/seller1.png' %}" alt="">
                <h1>𝑺𝒆𝒍𝒍𝒊𝒏𝒈 𝒘𝒊𝒕𝒉 𝑶𝒏𝒍𝒊𝒏𝒆</h1>
                
            </div>
            <div class="col-4">
                <p>How to Sell Your Product ? <br><i>________________________________</i></p><br>
                <span>1)    Completely understand the Product you're selling <br><br>
                2) Know your market and who will buy your product <br><br>
                3) Position the product as a solution to a problem or make something easier <br><br>
                4)Make your customer comfortable with you as a seller <br><br>
                5)Show first,then sell</span>
            </div>
        </div>
        <div class="row" id="row3">
            <div class="col-2"></div>
            <div class="col-8">
                <i class="fa-solid fa-quote-left" ></i>
               <P> WE WENT  FROM SALES OF 10,000 RUPEES TO 10 LAKH IN JUST TWO AND A HALF YEARS.</P>
               <i class="fa-solid fa-quote-right"></i>
            </div>
           
            <div class="col-2"></div>
        </div>
        <div class="row" id="row4">
            <h1>Seller Success story!</h1>
            <div class="col-2">
                <img src="{% static 'images/achiever.jpg' %}" alt="" width="100px">
            </div>
            <div class="col-10">
                <p> <span>Nishanth r:</span> <br>Startin with just one category,their unwavering support and innovative platform  empowered me to grow.
                    exponentialy expanding to six diverse categories and achieving an astounding  5x growth year on year.
                </p>

            </div>
        </div>
        <div class="row" id="row5">
            <div class="col-2">
                <img src="{% static 'images/achiever2.jpg' %}" alt="" width="100px">
            </div>
            <div class="col-10">
                <p><span>vishnu yash:</span><br>When moving from offline to online business, our aim wa to sell 300 oredrs per month.
                     Today we sell more than 700 per day and this has been possible bacause of the growth features on the fashionous sellerr dashboard ,fashionous ads and regular payments
                </p>
            </div>

        </div>
        <div class="row" id="row7">
                <div class="col-12">
                    <div id="address"> 
                    <p>Address: <br>Vaishnavi Summit, Ground Floor 7th Main 80 Feet Road,<br> 3rd block, Koramangala Industrial Layout,Banglore KA IN 560034</p>
                    </div>
                    <div id="about">
                      <p>About us: <br>We are a team of like-minded, passionate and innovative individuals with 10+ years of experience in the field of software.</p>
                    </div>
                    <div id="Contact">
                      <p>Contact Us: <br>
                        <a href="https://fashionous.in/" style="text-decoration: none; color: black;"><i class="fa-brands fa-google"></i>Google <br></a>
                        <a href="https://www.instagram.com/fashionous.in?igsh=dtduMmYzcDI4MXVz" style="text-decoration: none; color: black;"><i class="fa-brands fa-instagram"></i>instagram</a><br>
                        <i class="fa-brands fa-facebook"></i>facebook <br>
                        <i class="fa-brands fa-twitter"></i>twitter
                      </p>
        
                    </div>
                </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

seller/templates/seller/s_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/s_login.css' %}">
    <style>
        .container{
    height: 690px;
    text-align: center;
}
.row{
    height: 500px;
    margin-left: 100px;

}
.row button{
    width: 195px;
    height: 30px;
    border-radius: 3px;
}
button:hover{
    color: white;
    opacity: 0.5;
}
button{
    border: none;
    background-color:red;
}
    
.row .mrg{
    margin-top:100px;
}
input{
    width: 180px;
    height: 20px;
    border-top: none;
    border-left: none;
    border-right: none;
    background:none;
    font-size: medium;
}
input:hover{
    opacity: 0.5;
}
.col-7 img{
    background-size:cover;
    mix-blend-mode:darken;
    width: 450px;
    height: 500px;
}
.col-5{
    /* border: 1px solid black; */
    background-color: white;
    border-radius: 8px;
}
p{
    color: red;
}
.fa-solid .fa-user{
    opacity: 0.5;
}
a{
    text-decoration: none;
}
    </style>
</head>
<body style="background-color:#E5E8E8;">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <div class="container">
        <div class="row" >
            <div class="col-3"></div>
            <div class="col-5 mrg">
                <!-- <h1>Login</h1><br> -->
                <img src="{% static 'images/login_icon.jpg' %}" alt="" style="width: 170px;"><br>
                <table>
                    <form action="" method="post" onsubmit="return login()">
                        {% csrf_token %}
                        <input type="email" name="email" id="email" placeholder="Email"><i class="fa-solid fa-user"></i>
                        <p id="para"></p>
                        <input type="password" name="password" id="pass" placeholder="Password"><i class="fa-solid fa-lock"></i>
                        <p id="para1"></p><br><p>{{msg}}</p>
                        <button type="submit">Login</button>
                    </form>
                </table><br>
              
                <a href="">forgot password?</a>
                <a href="{% url 'seller:s_register' %}">create new account</a>
            </div>
            <div class="col-3">
                <!-- <img src="{% static 'images/IMG_20240120_194045.jpg' %}" alt=""> -->
            </div>

        </div>


    </div>
    <script>
        function login(){
        email=document.getElementById("email").value 
        paswrd=document.getElementById("pass").value
        if(email==""){
            document.getElementById("para").innerHTML="please enter email"
            return false

        // }else if(email=="@gmail.com"){
            // document.getElementById("para").value.hid
            // return false
        }else if(paswrd==""){
            document.getElementById("para1").innerHTML="please enter password"
            return false
        }else if(paswrd.length<6){
            document.getElementById("para1").innerHTML="please enter minimum 6 character"
            return false
        }return true
    }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

seller/templates/seller/view_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>
        #row1{
            background-color:#13B6B6 ;
        }
        #row1 table tr th{
            width: 200px;

        }
        #row1 table{
            margin-top: 40px;
            margin-left: 120px;
        }
        #row1 button{
            border: none;
            /* width: 160px; */
            background-color: #13B6B6;
        }
        button a{
            text-decoration:none;
            color: black;
            font-style: italic;
            font-weight: 700;
        }
        #row1 table button a:hover{
            background-color: black;
            color: white;
            border-radius: 5px;
        }
        #row2 table th{
            width: 200px;
            border: 1px solid black;
            text-align: center;
            font-size: larger;
            font-weight: 700;
        }
        #row2 table td{
            text-align: center;
            font-weight: 500;
            font-style: italic;
        }
        #row2 table{
            margin-top: 20px;
        }
        #profile{
            height: 35px;
            width: 35px;
            border-radius: 17px;
            background-color: black;
        }
        #profile a{
            text-align: center;
            font-size: larger;
            color: white;
            text-decoration:none;
            padding-left: 10px;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="row" id="row1">
            <div class="col-3">
                <img src="{% static 'images/fashionous_logo.jpg' %}" alt="" style="width: 250px; mix-blend-mode: darken;">
            </div>
            <div class="col-9">
                <form action="" method="post">
                    {% csrf_token %}
                    <table id="tabble1">
                        <tr>
                            <th><button style="margin-left: 70px;"><a href="{% url 'seller:s_home' %}">HOME</a></button></th>
                            <th><button><a href="{% url 'seller:add_product' %}">ADD PRODUCT</a></button></th>
                            <th><button><a href="{% url 'seller:view_product' %}">VIEW PRODUCT</a></button></th>
                            <!-- <th><button><a href="{% url 'seller:update_product' %}">UPDATE PRODUCT</a></button></th> -->
                            <th><button style="margin-left:20px;"><a href="{% url 'seller:s_login' %}">LOGIN</a></button></th>
                            <th><div id="profile"><a href="{% url 'seller:s_myaccount' %}">{{sell}}</a></div></th>
                            
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div class="row" id="row2">
            <div class="col-12">
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Images</th>
                        <th>Category</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for i in pdt %}
                    <tr>
                        <td>{{i.name}}</td>
                        <td>{{i.description}}</td>
                        <td>{{i.quantity}}</td>
                        <td>{{i.price}}</td>
                        <td><img src="{{i.image.url}}" alt="" width="80px"></td>
                        <td>{{i.category.name}}</td>
                        <td><a href="{% url 'seller:update_product' i.id %}" style="color: black;"><i class="fa-solid fa-pen"></i></a></td>
                        <td><a href="{% url 'seller:remove' i.id %}" style="color: black;"><i class="fa-solid fa-trash-can"></i></a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>